/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
};

export type ExperienceCard = {
  _id: string;
  _type: "experienceCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role?: string;
  company?: string;
  startDate?: string;
  isCurrent?: boolean;
  endDate?: string;
  summary?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  highlights?: Array<string>;
  order?: number;
};

export type AboutMe = {
  _id: string;
  _type: "aboutMe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  skills?: Array<{
    title?: string;
    items?: Array<string>;
    _type: "skillGroup";
    _key: string;
  }>;
  education?: Array<{
    institution?: string;
    degree?: string;
    year?: number;
    _key: string;
  }>;
  contactInfo?: {
    email?: string;
    linkedin?: string;
    github?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  liveUrl?: string;
  githubUrl?: string;
  technologies?: Array<string>;
  year?: number;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SiteSettings | ExperienceCard | AboutMe | SanityImageCrop | SanityImageHotspot | Project | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(defined(liveUrl) desc, order asc)[0...24]{  _id, title, "slug": slug.current, description, technologies, liveUrl, year}
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  technologies: Array<string> | null;
  liveUrl: string | null;
  year: number | null;
}>;
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{  title, description, technologies, githubUrl, liveUrl, year}
export type PROJECT_QUERYResult = {
  title: string | null;
  description: string | null;
  technologies: Array<string> | null;
  githubUrl: string | null;
  liveUrl: string | null;
  year: number | null;
} | null;
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(defined(liveUrl) desc, order asc){  "slug": slug.current, title, _updatedAt}
export type PROJECT_SLUGS_QUERYResult = Array<{
  slug: string | null;
  title: string | null;
  _updatedAt: string;
}>;
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experienceCard"] | order(order asc)[0...12]{  _id, role, company, startDate, endDate, isCurrent, highlights,  "summary": pt::text(summary)}
export type EXPERIENCE_QUERYResult = Array<{
  _id: string;
  role: string | null;
  company: string | null;
  startDate: string | null;
  endDate: string | null;
  isCurrent: boolean | null;
  highlights: Array<string> | null;
  summary: string;
}>;
// Variable: AboutPageQuery
// Query: *[_type == "aboutMe"][0]{  title, bio, education,  profileImage{    asset, hotspot, crop,    "lqip": asset->metadata.lqip,    "dimensions": asset->metadata.dimensions{width, height}  }}
export type AboutPageQueryResult = {
  title: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  education: Array<{
    institution?: string;
    degree?: string;
    year?: number;
    _key: string;
  }> | null;
  profileImage: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    lqip: string | null;
    dimensions: {
      width: number | null;
      height: number | null;
    } | null;
  } | null;
} | null;
// Variable: SKILLS_QUERY
// Query: *[_type == "aboutMe"][0].skills[defined(title)]{_key, title, items}
export type SKILLS_QUERYResult = Array<{
  _key: string;
  title: string | null;
  items: Array<string> | null;
}> | null;
// Variable: CONTACT_INFO_QUERY
// Query: *[_type == "aboutMe"][0].contactInfo{email, linkedin, github}
export type CONTACT_INFO_QUERYResult = {
  email: string | null;
  linkedin: string | null;
  github: string | null;
} | null;
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  "heroVideoUrl": heroVideo.asset->url}
export type SITE_SETTINGS_QUERYResult = {
  heroVideoUrl: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"project\" && defined(slug.current)] | order(defined(liveUrl) desc, order asc)[0...24]{\n  _id, title, \"slug\": slug.current, description, technologies, liveUrl, year\n}": PROJECTS_QUERYResult;
    "*[_type == \"project\" && slug.current == $slug][0]{\n  title, description, technologies, githubUrl, liveUrl, year\n}": PROJECT_QUERYResult;
    "*[_type == \"project\" && defined(slug.current)] | order(defined(liveUrl) desc, order asc){\n  \"slug\": slug.current, title, _updatedAt\n}": PROJECT_SLUGS_QUERYResult;
    "*[_type == \"experienceCard\"] | order(order asc)[0...12]{\n  _id, role, company, startDate, endDate, isCurrent, highlights,\n  \"summary\": pt::text(summary)\n}": EXPERIENCE_QUERYResult;
    "*[_type == \"aboutMe\"][0]{\n  title, bio, education,\n  profileImage{\n    asset, hotspot, crop,\n    \"lqip\": asset->metadata.lqip,\n    \"dimensions\": asset->metadata.dimensions{width, height}\n  }\n}": AboutPageQueryResult;
    "*[_type == \"aboutMe\"][0].skills[defined(title)]{_key, title, items}": SKILLS_QUERYResult;
    "*[_type == \"aboutMe\"][0].contactInfo{email, linkedin, github}": CONTACT_INFO_QUERYResult;
    "*[_type == \"siteSettings\"][0]{\n  \"heroVideoUrl\": heroVideo.asset->url\n}": SITE_SETTINGS_QUERYResult;
  }
}
